---
title: "CM Project"
author: "CHAN Wai Nok"
date: '2023-10-07'
output: github_document
---
``` {r}
library(metafor)
library(readxl)
```

### Data
``` {r}
data = read_excel("Data_final.xlsx")
knitr::kable(data, format = 'markdown')
data = escalc(measure = 'RR', ai = cancer_screen, n1i = n_screen, ci = cancer_control, n2i = n_control, slab = paste(Author, ', ', Year, sep=''), data = data)
knitr::kable(data, format = 'markdown')
```

### Random-effects model
``` {r}
res = rma(yi, vi, data = data)
res
predict(res, transf = exp, digits = 2) # prediction interval
```

### Results
``` {r}
# generate forest plot (adjust the arguments as needed)
forest(res, atransf=exp, addpred = T, mlab="", shade=TRUE,
       at=log(c(0.2, 0.5, 1, 2, 4, 8)), 
       xlim=c(-16,6),
       ilab=cbind(cancer_screen, n_screen, cancer_control, n_control), ilab.xpos=c(-9.5,-8,-6,-4.5),
       cex=0.7,
       header="Authors and Year")

# labels of study design
op = par(cex=0.75, font=2)
text(c(-9.5,-8,-6,-4.5), res$k+2, c("Cancer", "Total", "Cancer", "Total"))
text(c(-8.75,-5.25),     res$k+3, c("Screening", "Control"))
par(op)
 
# Q-value, dfs, p-value, and I^2 statistic
text(-16, -0.55, pos=4, cex=0.75, "RE Model")
text(-16, -1.5, pos=4, cex=0.75, bquote(paste(
     "(Q = ", .(fmtx(res$QE, digits=2)),
     ", df = ", .(res$k - res$p), ", ",
     .(fmtp(res$QEp, digits=3, pname="p", add0=TRUE, sep=TRUE, equal=TRUE)),
     "; ", I^2, " = ", .(fmtx(res$I2, digits=1)), "%)")))
```

### Publication bias
``` {r}
# funnel plots
funnel(res, main="Funnel plot", las=1, digits=list(1L, 1))
# contour-enhanced funnel plot
funnel(res, main="Contour-enhanced funnel plot",level=c(90, 95, 99), shade=c("white", "gray55", "gray75"), las=1, digits=list(1L, 1), legend=TRUE, refline = 0)

# Egger's regression test
regtest(yi, vi, data=data, ret.fit = T)

# Trim-and-fill method
res.new = trimfill(res)
res.new

forest(res.new, atransf=exp, addpred = T, mlab="", shade=TRUE,
       at=log(c(0.2, 0.5, 1, 2, 4, 8)), 
       cex=0.7,
       header="Authors and Year")
text(-5.85, -0.55, pos=4, cex=0.75, "RE Model")
text(-5.85, -1.5, pos=4, cex=0.75, bquote(paste(
     "(Q = ", .(fmtx(res.new$QE, digits=2)),
     ", df = ", .(res.new$k - res.new$p), ", ",
     .(fmtp(res.new$QEp, digits=3, pname="p", add0=TRUE, sep=TRUE, equal=TRUE)),
     "; ", I^2, " = ", .(fmtx(res.new$I2, digits=1)), "%)")))

funnel(res.new, las = 1, digits = list(1L, 1), legend = T)
```








